---
abstract: 'RT Extension-ActivityReports Extension'
author:
  - 'Alex Vandiver <alexmv@bestpractical.com>'
build_requires:
  ExtUtils::MakeMaker: 6.36
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.04'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: RT-Extension-ActivityReports
no_index:
  directory:
    - html
    - inc
requires:
  Time::Duration: 0
resources:
  license: http://dev.perl.org/licenses/
version: 1.02
