---
abstract: 'RT-Extension-ActivityReports Extension'
author:
  - 'Best Practical Solutions, LLC <modules@bestpractical.com>'
build_requires:
  ExtUtils::MakeMaker: 6.59
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.08'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: RT-Extension-ActivityReports
no_index:
  directory:
    - html
    - inc
requires:
  Time::Duration: 0
  perl: 5.8.3
resources:
  license: http://dev.perl.org/licenses/
version: '1.04'
x_module_install_rtx_version: 0.34_04
x_requires_rt: 4.0.0
x_rt_too_new: 4.4.0
